### ISSUE TITLE
Question: Can I use django cache for data caching on the client side ?

### ISSUE THREAD

**Issue by frague59** [wagtail/queryish#1]
Hi, 

Thanks for this great package !

I've an API endpoint (DRF driven) I want to get data from, and I would like to use `queryish` to grab these data no another django (wagtail) app.

Can I use `django.core.cache`  on the client side to globally store these data to accelerate data retrieval without performing API queries ?

Thanks for your help !

**Comment by gasman** [comment]
All API requests made by `APIQuerySet` go through a single `fetch_api_response` method, which [caches previous API responses on the queryset object](https://github.com/wagtail/queryish/blob/8448d41c9a2a42430d73a7da858ad3852068893d/queryish/rest.py#L170-L176) to avoid repeated requests - if you wanted a global cache instead, you could override `fetch_api_response` to provide that. I don't think we'd want to do that within `queryish` itself, as it would introduce a dependency on Django with not much benefit.
